DROP INDEX IDX_TBL_COMMENT_REACTION_COMMENT ON TBL_COMMENT_REACTION;

ALTER TABLE TBL_COMMENT_REACTION DROP COLUMN DEL_YN;

CREATE INDEX IDX_TBL_COMMENT_REACTION_COMMENT ON TBL_COMMENT_REACTION (COMMENT_ID, REACTION_TYPE);